### ISSUE TITLE
Feature Request (Add Placeholder support to the message) 

### ISSUE THREAD

**Issue by VacAge** [spigot-gillesm/rpg-chest#21]
It would be great to add PlaceholderAPI support in Event, for example `%player%`
Example:
```
events:
  message:
    trigger: ON_OPEN
    radius: 100
    text:
    - "&7%player% found an Rare Chest"
```
