### ISSUE TITLE
Feature Request (Add Commands support to the Events) 

### ISSUE THREAD

**Issue by VacAge** [spigot-gillesm/rpg-chest#22]
It would be great to add support for executing commands in Event
Example:
```
events:
  command:
    trigger: ON_OPEN
    command:
    - "mi browse %player%"
    - "effect give %player% blindness 1"
```
