### ISSUE TITLE
Bug with MMOItems support (Types of items)

### ISSUE THREAD

**Issue by VacAge** [spigot-gillesm/rpg-chest#23]
In MMOItems, there are not just item IDs, for example KATANA, but also the types of items through which you need to find the item. At the moment, adding items is done only through ID, but it's right to do it like everyone else. Since if I add another item with ID KATANA but it will lie in a different type of item, RPGChest will look for one of the two. You need to add support specify the type of item then ID
Example:
```
amount: 1-2
items:
  steel_ingot:
    chance: 1
    amount: 1
    item: mi:MATERIAL.STEEL_INGOT ##Type - MATERIAL, ID - STEEL_INGOT
```
